### ISSUE TITLE
bedgraph sliding window should count absolute number of binding sites

### ISSUE THREAD

**Issue by sesh-sas** [eclarke/swga#10]
In the bedgraph output, we should be measuring the absolute number of binding sites within a window, not the average.  As we expect 1 binding site at most every kilobase, average would yield a very small number

**Comment by eclarke** [comment]
fixed in 49ee0dcd764611261475c1fae24c77fd7e246529

**Comment by drbrisson** [comment]
Sesh. Can you add the output to bedgraph and bedgraph instructions to the
online wiki manual. Either its own page or at the bottom of home page

**Comment by sesh-sas** [comment]
I am planning to have an example of this in the example workflow page, but we can also do another page just dedicated to export, since there are a lot of options.

Sesh

**Comment by drbrisson** [comment]
I think a link-out page is probably better. It is not the primary function
but more of a check on the primary function. It will also keep the quick
start guide looking more like a quick start, it is getting pretty hefty
already
