### ISSUE TITLE
init should prompt for "fasta files from which to exclude primers (e.g. mitochondria)"

### ISSUE THREAD

**Issue by seifst** [eclarke/swga#13]
init should prompt for "fasta files from which to exclude primers (e.g. mitochondria)"

At the very least the QuickStart should mention the command for including a file from which to exclude primers that bind to the mitochondria as this will be common to nearly all projects.

**Comment by drbrisson** [comment]
I think we can all edit the QuickStart guide. I would suggest we each make
the changes we would like to see and let everyone know what we have done on
this email chat.
It records a history so if we all do not agree on a change, we can go back
in time.
d

**Comment by seifst** [comment]
I think it would be better to have init prompt for the file along with the fg and bg.

**Comment by eclarke** [comment]
aa9afcd127ec8d152576c29c458ff569b5ecb16e: Init command updated to prompt/accept exclusionary sequences FASTA file
