### ISSUE TITLE
DSK merges kmers and reverse complements

### ISSUE THREAD

**Issue by sesh-sas** [eclarke/swga#17]
Since most properties of kmers and their RCs will be the same, this is fine through `swga filter`.

However sets may exist that can include primerA and primerB(RC) but not primerA and primerB (due to heterodimer checks).

So we need to include the RC of active primers in `swga find_sets`

**Comment by eclarke** [comment]
All reverse complements are added during `swga count` for simplicity. Fixed in 2721611847cb332d399a2d1b0d2dd8e294402c9b
