### ISSUE TITLE
Change parameters named bg_ratio

### ISSUE THREAD

**Issue by sesh-sas** [eclarke/swga#21]
Historically we have used bg_ratio (bg genome length / # of binding sites) as an approximation of average bg binding distance.  We have called this bg_ratio to be mathematically correct.  I think we should simply change this to bg_dist_mean in the scores output.

We can mention that our calculation is an approximation of mean distance in the docs and that we use the approximation because calculating a true average would get very complicated when using genomes that are not complete assemblies, etc.

Also our parameter for this is actually:
min_bg_bind_dist: minimum allowable AVERAGE distance between primers in the background dataset. Larger distances between priming sites result in lower levels of amplification by the phi29 enzyme. However, this enzyme has high processivity (~70kb), so the primers may need to be quite far apart.
Note that this is an AVERAGE distance, thus some areas of the background may be amplified despite a large values for this parameter.

so we are already halfway to considering it as an approximation of the average.

**Comment by drbrisson** [comment]
I agree. That parameter name always confuses me

**Comment by sesh-sas** [comment]
Updated in c686cc98539ca2cba4e2e5bc648d44002463ba87
