### ISSUE TITLE
bedgraph output sliding window

### ISSUE THREAD

**Issue by sesh-sas** [eclarke/swga#22]
The current bedgraph output uses a window to calculate the number of binding sites and a step size to move the window.

The output positions should be based on the step size rather than the window size.  The current output generates overlapping segments in the bedgraph that are confusing.

track type=bedGraph None
gi 0 5001 0
gi 1000 6001 0
gi 2000 7001 0
gi 3000 8001 0
gi 4000 9001 0
gi 5000 10001 0

**Comment by eclarke** [comment]
I suppose the easiest way to do this is to condense it into points at the midpoint of each window?

**Comment by sesh-sas** [comment]
I agree

**Comment by sesh-sas** [comment]
The output now outputs the midpoint of the sliding window in columns 2 (start) and 3 (end) of the bedgraph format.

**Comment by sesh-sas** [comment]
The output now outputs the midpoint of the sliding window in columns 2 (start) and 3 (end) of the bedgraph format.
In https://github.com/eclarke/swga/commit/6f0c5c530979aa931372f39d58073becbdfa4b1e
