### ISSUE TITLE
Backwards compatible, Python error with new version of swga and old version files

### ISSUE THREAD

**Issue by stsmall** [eclarke/swga#30]
Hi,
I created primer sets using an older version of swga. When I updated swga to the new version (for bug fixes) commands no longer seem to work on the old files. Py.test produces no errors and it works properly on files created under the same version. The python error is:
Traceback (most recent call last):
  File "/home/smalls/anaconda/bin/swga", line 9, in <module>
    load_entry_point('swga==0.3.6', 'console_scripts', 'swga')()
  File "/home/smalls/anaconda/lib/python2.7/site-packages/swga/commands/swga_entry.py", line 61, in main
    command_opts[args.command](remaining, args.config)
  File "/home/smalls/anaconda/lib/python2.7/site-packages/swga/commands/summary.py", line 13, in main
    summary(**cmd.args)
  File "/home/smalls/anaconda/lib/python2.7/site-packages/swga/commands/summary.py", line 48, in summary
    bs = Set.select().order_by(Set.score).limit(1).get()
  File "/home/smalls/anaconda/lib/python2.7/site-packages/peewee.py", line 2595, in get
    return clone.execute().next()
  File "/home/smalls/anaconda/lib/python2.7/site-packages/peewee.py", line 2636, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/home/smalls/anaconda/lib/python2.7/site-packages/peewee.py", line 2325, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/smalls/anaconda/lib/python2.7/site-packages/peewee.py", line 3015, in execute_sql
    self.commit()
  File "/home/smalls/anaconda/lib/python2.7/site-packages/peewee.py", line 2864, in __exit__
    reraise(new_type, new_type(*exc_value.args), traceback)
  File "/home/smalls/anaconda/lib/python2.7/site-packages/peewee.py", line 3007, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such column: t1.bg_dist_mean

any thoughts?

**Comment by eclarke** [comment]
Hey there, 
The most recent version of SWGA uses a different database format than the previous versions to address certain issues. As a consequence, it looks like it broke compatibility with old workspaces (which wasn't my intention).

The easiest way to get around this is to add your existing primer sets to swga by following the instructions here: 
https://github.com/eclarke/swga/wiki/Using-a-custom-list-of-primers-for-finding-or-scoring-specific-sets.

This will add specific sets of primers to your workspace and score them correctly so that you can use them as before. 

Please let me know if this helps, and sorry for the inconvenience!

**Comment by stsmall** [comment]
Hi Erik,
What is the format of the input primer file?
Following the link named my_primers.txt.
thanks,
scott

On 10/20/15 12:26 PM, Erik Clarke wrote:
> Hey there,
> The most recent version of SWGA uses a different database format than 
> the previous versions to address certain issues. As a consequence, it 
> looks like it broke compatibility with old workspaces (which wasn't my 
> intention).
>
> The easiest way to get around this is to add your existing primer sets 
> to swga by following the instructions here:
> https://github.com/eclarke/swga/wiki/Using-a-custom-list-of-primers-for-finding-or-scoring-specific-sets.
>
> This will add specific sets of primers to your workspace and score 
> them correctly so that you can use them as before.
>
> Please let me know if this helps, and sorry for the inconvenience!
>
> > On Oct 20, 2015, at 11:59 AM, stsmall <notifications@github.com> wrote:
> >
> > Hi,
> > I created primer sets using an older version of swga. When I updated 
> swga to the new version (for bug fixes) commands no longer seem to 
> work on the old files. Py.test produces no errors and it works 
> properly on files created under the same version. The python error is:
> > Traceback (most recent call last):
> > File "/home/smalls/anaconda/bin/swga", line 9, in
> > load_entry_point('swga==0.3.6', 'console_scripts', 'swga')()
> > File 
> "/home/smalls/anaconda/lib/python2.7/site-packages/swga/commands/swga_entry.py", 
> line 61, in main
> > command_optsargs.command
> > File 
> "/home/smalls/anaconda/lib/python2.7/site-packages/swga/commands/summary.py", 
> line 13, in main
> > summary(*cmd.args)
> > File 
> "/home/smalls/anaconda/lib/python2.7/site-packages/swga/commands/summary.py", 
> line 48, in summary
> > bs = Set.select().order_by(Set.score).limit(1).get()
> > File "/home/smalls/anaconda/lib/python2.7/site-packages/peewee.py", 
> line 2595, in get
> > return clone.execute().next()
> > File "/home/smalls/anaconda/lib/python2.7/site-packages/peewee.py", 
> line 2636, in execute
> > self.qr = ResultWrapper(model_class, self.execute(), query_meta)
> > File "/home/smalls/anaconda/lib/python2.7/site-packages/peewee.py", 
> line 2325, in _execute
> > return self.database.execute_sql(sql, params, self.require_commit)
> > File "/home/smalls/anaconda/lib/python2.7/site-packages/peewee.py", 
> line 3015, in execute_sql
> > self.commit()
> > File "/home/smalls/anaconda/lib/python2.7/site-packages/peewee.py", 
> line 2864, in __exit
> > reraise(new_type, new_type(exc_value.args), traceback)
> > File "/home/smalls/anaconda/lib/python2.7/site-packages/peewee.py", 
> line 3007, in execute_sql
> > cursor.execute(sql, params or ())
> > peewee.OperationalError: no such column: t1.bg_dist_mean
> >
> > any thoughts?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/eclarke/swga/issues/30#issuecomment-149639732>.
>

-- 
Every  gun  that is made,  every warship launched,
every rocket fired signifies,in the final sense,
a theft from those who hunger and are
not fed, those who are cold and are
not clothed. This world in arms is
not spending money alone. It is
spending the sweat of its
laborers, genius of its
scientists, the hopes
of its children.
--Dwight D. Eisenhower

**Comment by eclarke** [comment]
The file should just be one primer per line, nothing else, eg:
```bash
$ cat my_primers.txt
ATGCATGC
CCTTAAGG
ATTTCCG
```

**Comment by stsmall** [comment]
Hi Erik,
When I run the commands, count looks fine but then activate and score 
both report errors.
$ swga count --input primers.txt
Command: count
- fg_genome_fp: 
/home/smalls/swga_new/Wb_v_Hg19-contigs/WbHg19-2/Wb-PNG_Genome_assembly-pt22.500-cleanNCBI.fasta
- exclude_fp: /home/smalls/swga_new/Wb-PNG_mtGenome.fa
- max_dimer_bp: 3
- bg_genome_fp: /home/smalls/swga_new/Hg19.fa
- min_fg_bind: 903
- min_size: 5
- input: <open file 'primers.txt', mode 'r' at 0x2aec9cb0b300>
- exclude_threshold: 1
- max_bg_bind: 21369
- max_size: 12
- primer_db: primers.db
AACGATAATA already exists in db, skipping...
AATCGATAAT already exists in db, skipping...
ATCGATGAAA already exists in db, skipping...
ATGATAACGA already exists in db, skipping...
CGAAATAATT already exists in db, skipping...
CGACGAAT already exists in db, skipping...
CGATACGA already exists in db, skipping...
CGCGAAAA already exists in db, skipping...
CGTAAACG already exists in db, skipping...
GACGAAAAAA already exists in db, skipping...
TCGAACGA already exists in db, skipping...
TTCGAAAAAAA already exists in db, skipping...

$ swga activate --input primers.txt
Command: activate
- reset: False
- input: <open file 'primers.txt', mode 'r' at 0x2b60924f0390>
- bg_genome_fp: /home/smalls/swga_new/Hg19.fa
- fg_genome_fp: 
/home/smalls/swga_new/Wb_v_Hg19-contigs/WbHg19-2/Wb-PNG_Genome_assembly-pt22.500-cleanNCBI.fasta
- primer_db: primers.db
Traceback (most recent call last):
   File "/home/smalls/anaconda/bin/swga", line 9, in <module>
     load_entry_point('swga==0.3.6', 'console_scripts', 'swga')()
   File 
"/home/smalls/anaconda/lib/python2.7/site-packages/swga/commands/swga_entry.py", 
line 61, in main
     command_opts[args.command](remaining, args.config)
   File 
"/home/smalls/anaconda/lib/python2.7/site-packages/swga/commands/activate.py", 
line 17, in main
     swga.database.Primer.update_Tms(primers)
AttributeError: type object 'Primer' has no attribute 'update_Tms'

$ swga score --input primers.txt
Command: score
- fg_genome_fp: 
/home/smalls/swga_new/Wb_v_Hg19-contigs/WbHg19-2/Wb-PNG_Genome_assembly-pt22.500-cleanNCBI.fasta
- bg_genome_len: 3189447329
- score_expression: (fg_dist_mean * fg_dist_gini) / (bg_dist_mean)
- bg_genome_fp: /home/smalls/swga_new/Hg19.fa
- input: <open file 'primers.txt', mode 'r' at 0x2b419f928390>
- primer_db: primers.db
Set statistics:
  - bg_dist_mean....:    190,734
  - fg_max_dist.....:     55,693
  - scoring_fn......: (fg_dist_mean * fg_dist_gini) / (bg_dist_mean)
  - score...........:  0.0123522
  - fg_dist_gini....:   0.624903
  - fg_dist_std.....:   5,042.68
  - fg_dist_mean....:   3,770.14
  - set_size........:         12
Add set to database? [y/N]: y
Traceback (most recent call last):
   File "/home/smalls/anaconda/bin/swga", line 9, in <module>
     load_entry_point('swga==0.3.6', 'console_scripts', 'swga')()
   File 
"/home/smalls/anaconda/lib/python2.7/site-packages/swga/commands/swga_entry.py", 
line 61, in main
     command_opts[args.command](remaining, args.config)
   File 
"/home/smalls/anaconda/lib/python2.7/site-packages/swga/commands/score.py", 
line 40, in main
     interactive=True)
   File 
"/home/smalls/anaconda/lib/python2.7/site-packages/swga/commands/score.py", 
line 85, in score_set
     set_id = Set.select(fn.Min(Set._id)).scalar() - 1
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

On 10/21/15 10:48 AM, Erik Clarke wrote:
>
> The file should just be one primer per line, nothing else, eg:
>
> $ cat my_primers.txt
> ATGCATGC
> CCTTAAGG
> ATTTCCG
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/eclarke/swga/issues/30#issuecomment-149939330>.
>

-- 
Every  gun  that is made,  every warship launched,
every rocket fired signifies,in the final sense,
a theft from those who hunger and are
not fed, those who are cold and are
not clothed. This world in arms is
not spending money alone. It is
spending the sweat of its
laborers, genius of its
scientists, the hopes
of its children.
--Dwight D. Eisenhower

**Comment by eclarke** [comment]
Could you try making a new workspace (following the install instructions again, but with a different folder name), and then adding these primers to the fresh workspace? There seems to be some kind of conflict between what's already there and what we're trying to do. Sorry about that...

**Comment by eclarke** [comment]
Hi @stsmall, I fixed a bug in `swga activate` that was causing your latter problem. Please let me know if things work for you now.
