### ISSUE TITLE
Problem with swga filter

### ISSUE THREAD

**Issue by jonbparr** [eclarke/swga#37]
Hi,

I keep getting an error message when I attempt to use the "swga filter" command. Here's the end of the error message -- happy to post the entire traceback error message if needed:

"  File "~/swga_workspace/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: near "?": syntax error"

No problems with swga init or swga count, but I get this message when I try swga filter every time.  I'm using python 2.7.6, as suggested in the install instructions, and I've installed the most recent swga update.  Looks like there may be a problem with the melting temperature filters or with peewee?

Open to ideas/suggestions.  Thanks!

Jonathan

**Comment by eclarke** [comment]
Hi Jonathan, that's odd. Could you post the entire traceback?

**Comment by jonbparr** [comment]
$ swga filter

swga filter, v0.4.3
  - max_gini: 0.6
  - min_tm: 25.0
  - max_primers: 200
  - max_tm: 75.0
  - min_fg_bind: 237
  - input: None
  - skip_filtering: False
  - max_bg_bind: 21928
31768/31768 primers bind the foreground genome >= 237 times
31768/31768 primers bind the background genome <= 21928 times
31768 primers satisfy all filters so far.

Traceback (most recent call last):
  File "~/swga_workspace/bin/swga", line 9, in <module>
    load_entry_point('swga==0.4.3', 'console_scripts', 'swga')()
  File "~/swga_workspace/lib/python2.7/site-packages/swga/main.py", line 81, in main
    setup_and_run(cmd_class, args.command, remaining)
  File "~/swga_workspace/lib/python2.7/site-packages/swga/main.py", line 49, in setup_and_run
    cmd.run()
  File "~/swga_workspace/lib/python2.7/site-packages/swga/commands/filter.py", line 37, in run
    .filter_tm_range(self.min_tm, self.max_tm)
  File "~/swga_workspace/lib/python2.7/site-packages/swga/primers.py", line 24, in func
    results = fn(self, *args, **kwargs)
  File "~/swga_workspace/lib/python2.7/site-packages/swga/primers.py", line 157, in filter_tm_range
    self.update_melt_temps()
  File "~/swga_workspace/lib/python2.7/site-packages/swga/primers.py", line 39, in func
    targets = fn(self, *args, **kwargs)
  File "~/swga_workspace/lib/python2.7/site-packages/swga/primers.py", line 246, in update_melt_temps
    (Primer.tm >> None)))
  File "~/swga_workspace/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "~/swga_workspace/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "~/swga_workspace/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "~/swga_workspace/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "~/swga_workspace/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "~/swga_workspace/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: near "?": syntax error

**Comment by eclarke** [comment]
Hm, thanks. In the same virtualenv and directory you use for swga, could you run `pip freeze` and paste the output here as well? I wonder if a dependency has been updated. 

Also, could you try varying the melting temperatures you have set and reporting if anything changes? 
(By the way, the defaults for the melt temps are actually not ideal. For our experiments, we usually have them set to 15C-45C. I'll be changing the defaults in an update soon, but just thought you should know.)

**Comment by jonbparr** [comment]
Thanks for your help! Here's the pip freeze output:

"You are using pip version 6.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
argutils==0.3.2
click==6.6
melt==1.0.3
peewee==2.8.1
py==1.4.31
pyfaidx==0.4.7.1
pytest==2.9.2
PyYAML==3.11
semantic-version==2.5.0
six==1.10.0
swga==0.4.3"

Made the melt temp change, but still running into the same error.  I hadn't customized any of the other filters yet -- really helpful to learn from your experience.

**Comment by eclarke** [comment]
I don't see any differences between your dependency versions and mine, so I don't think it's an error with peewee. Would you be able to send me your complete setup (fg & bg genome, parameters.cfg file, and OS version)? If you want to send them privately as a dropbox/google drive link or something like that, my email is ecl [at] mail.med.upenn.edu. I will delete them as soon as the issue is resolved.

**Comment by jonbparr** [comment]
Many thanks!  I'll send you an email with all of the above.

**Comment by jonbparr** [comment]
Thanks for your help with this.  My problem appears to have been specific to our cluster -- I'm now up and running on my local machine.  Only tweak was creating a virtual environment using miniconda, although I suspect the original install instructions would have worked on my local machine as well.
