### ISSUE TITLE
SWGA error related to dependencies

### ISSUE THREAD

**Issue by eclarke** [eclarke/swga#41]
From @saclarkPHE:

Hi,

I'm also having problems running the programme. After a seemingly successful installation, I run the swga command and get:

Traceback (most recent call last):
File "/home/ste/miniconda2/bin/swga", line 4, in 
import swga.main
File "/home/ste/miniconda2/lib/python2.7/site-packages/swga/main.py", line 9, in 
import workspace
File "/home/ste/miniconda2/lib/python2.7/site-packages/swga/workspace.py", line 161, in 
class Set(SwgaModel):
File "/home/ste/miniconda2/lib/python2.7/site-packages/swga/workspace.py", line 170, in Set
primers = ManyToManyField(Primer, related_name='sets')
TypeError: init() got an unexpected keyword argument 'related_name'

Ive tried the method outlined in the installation instructions (within Virtualenv) and using miniconda but with the same TypeError in init. I'm running Python 2.7.14 and GCC 5.4.0.

Any help would be appreciated. I'm a complete Linux/command line noob so the more idiot proof the better.

Many thanks!

**Comment by eclarke** [comment]
Thanks for reporting this, @saclarkPHE. I've fixed it in 2f240cbb356d8c4b4130d9e442596d10227738ff.

The issue was that a dependency was updated by accident. Please try re-installing SWGA and seeing if that works.

**Comment by saclarkPHE** [comment]
Thanks very much!
