### ISSUE TITLE
GC content

### ISSUE THREAD

**Issue by kaushia** [eclarke/swga#43]
Dear author, 
It is obvious that GC content of the foreground genome is very important for swga primer identification, like you mentioned for the P vivax genome in the first swga publication (Cowell et al. 2017;mBio 8:e02257-16). I wonder how did the authors decided reference/foreground genomic regions with high GC content and poor coverage for designing swga primers. Authors mentioned:

"longer regions (>195,000 bp) of the P. vivax reference genome (Sal-1) that were GC rich (48.5 to 50.6%) and yielded low genome coverage" 

I am unable to find the methodology authors used to decide the long genome regions  and what methodology should I use to calculate the GC content in that region (e.g. kmer size). I am standardising the methodology so that I could use swga tool for my own plasmodium sp., however I am unable to replicate P vivax genome results. 

Please help me. Thank you.

**Comment by sesh-sas** [comment]
It would be best to direct questions regarding the Cowell paper to the corresponding author or first author of that paper. GC content across the genome would be best calculated using a sliding scale that looks at GC content over thousands of basepairs. At least initially you may also want to design primers that amplify the entire genome and then look for gaps in coverage and redesign primers to target those regions.
