### ISSUE TITLE
Filter primers that bind a given genome or from a list

### ISSUE THREAD

**Issue by sesh-sas** [eclarke/swga#6]
We should be able to provide a fasta sequence or list of primers and filter them.  For the fasta it would be good if we set a limit for filtering. I.e. If the primer occurs more than once in the file then filter it. The list should be completely filtered since it's a list.

**Comment by eclarke** [comment]
The new version allows you to specify a FASTA file using `swga count --exclude_fp`. No primers that bind anywhere in this file will be added to the database. Let me know if this works for you.
